version: '3'

services:
  app:
    build: .
    container_name: nextjs
    # entrypoint: sh -c "npm run build && npm run start" 
    entrypoint: sh -c "npm install && npm run dev" 
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
